### ISSUE TITLE
Double-spaced UTF characters break song duration display

### ISSUE THREAD

**Issue by rod98** [MusicPlayerDaemon/ncmpc#64]
Situation: I have a song in the queue with a very long title that consists of both Japaneese (kanji) and English characters, so some of them are 2 spaces in width. 

Current behavior: when terminal window width is even, it may happen that the last displayed character of the title is a two-spaced kanjii. In this case, after displaying the song title, `ncmpc` tries to print its duration (6:03), but the remaining place is not enough, so only 6:0 stays on the same line, and 3 goes to the next one.
Problem occurs both with `scroll=0` and `scroll=1`

Expected behavior: if the last displayed character occupies two spaces, it is replaced by a space so that the duration fits in the line.

**Comment by MaxKellermann** [comment]
This is an interesting bug, because ncmpc appears to be correct - it correctly calculates the coordinates for the song duration and writes the duration text there - but libncurses offsets the given column by one, because the column is occupied by the second cell of a wide character. I'll try to find some libncurses documentation about this problem, but right now, it looks like a libncurses bug.

**Comment by MaxKellermann** [comment]
After debugging this back and forth, with and without libncurses, I am finally convinced that this is really a libncurses bug.
When moving the cursor to the middle of a wide character and printing data there, libncurses should erase the whole wide character (even the portion that is not being overwritten, because there are no "partial wide characters"). But what libncurses does instead is keep the wide character and pretend the right half doesn't exist - from the terminal's point of view, however, it still exists and so the terminal prints the following text off by one to the right, causing the bug you described.
Sorry, this must be fixed in libncurses.
