### ISSUE TITLE
random crashes with ncmpc 0.28 on Alpine Linux

### ISSUE THREAD

**Issue by nmeum** [MusicPlayerDaemon/ncmpc#9]
When running ncmpc and suspending my laptop ncmpc (sometimes) crashes as soon as my laptop wakes up from sleep again. The following output shows up on stdout in that case:

```
Assertion failed: c->source != NULL (../src/mpdclient.c: mpdclient_schedule_enter_idle: 52)
                                                                           Aborted
```

**Comment by MaxKellermann** [comment]
Reporting bugs on old version wastes developer's time, and you should feel bad about it.

**Comment by MaxKellermann** [comment]
Oh-oh-oh. This time I feel terribly bad and sorry. A very similar message was reported many times to me, and was caused by an outdated ncmpc+libmpdclient version, because many distributions wouldn't update these versions. What you have looks indeed like a different bug on the second sight. Sorry again.

**Comment by MaxKellermann** [comment]
911d7e95dc5f469938a6d06786f7c6651df02e17
